### ISSUE TITLE
Data seems to be not ready in IR.data

### ISSUE THREAD

**Issue by DerMambo** [meteorhacks/fast-render#10]
Hi Arunoda,

I added FR to my project and it works but in this case.

I have a route for a blog post like this:

    @route 'blogPost',
      path: '/blog/:slug'
      waitOn: -> Meteor.subscribe('postFull', @params.slug)
      fastRender: true
      data: ->
        return null unless @ready()
        post = Posts.findOne({slug: @params.slug})
        author = Authors.findOne({_id: post.author})
        return {post: post, author: author}
      after: ->
        return unless Meteor.isClient
        post = @data().post
        SEO.set({
          title: post.title
          description: post.description
          og:
            title: post.title
            description: post.description
        })

The publication of 'postFull' looks like this:

    Meteor.publish('postFull', (slug) ->
      post = Posts.find({slug: slug})
      postArr = post.fetch()
      return [] unless postArr.length > 0
      author = Authors.find({_id: postArr[0].author})
      return [post, author]
    )

This works without FR. The problem is, that in the data function post is undefined. It seems the subscriptions are not ready or not available through the collection in the data function even though I ask if the subscriptions are ready with 'this.ready()'.

**Comment by arunoda** [comment]
Hope we are good here.
