### ISSUE TITLE
waitOn and publication called hundreds of times

### ISSUE THREAD

**Issue by lorensr** [meteorhacks/fast-render#106]
```coffeescript
home_subs = new SubsManager
  cacheLimit: 9999
  expireIn: 9999

Router.configure
  waitOn: ->
    console.log 'global waitOn'
    datasub = home_subs.subscribe 'data'

Meteor.publish 'data', ->
  console.log 'in data publishing, user: ', @userId
  Items.find {}
```

When I add `fast-render` and load the app, this global `waitOn` and the `data` publication are run continuously (hundreds of log prints) for a few seconds until the page loads. This happens even on routes that do not have `fastRender: true`. I assume this is not normal? 

`FastRender.debugger.getPayload()` shows 

![image](https://cloud.githubusercontent.com/assets/251288/7193402/f14f275a-e454-11e4-93e4-567aa98b7981.png)

`collectionData` has all the right data, but `subscriptions` is empty. 

What can I do to debug the problem?

**Comment by arunoda** [comment]
Not sure why router reruns a lot of times. Check server logs while this
happens.

I can't see anything wrong with this.

**Comment by lorensr** [comment]
The only thing being logged is a lot of this, from the `console.log`s shown above:

```
I20150416-16:27:15.245(-7)? global waitOn
I20150416-16:27:15.245(-7)? in data publishing, user: 
I20150416-16:27:15.245(-7)? FuFa6muAquumzfLMC
I20150416-16:27:15.261(-7)? global waitOn
I20150416-16:27:15.261(-7)? in data publishing, user: 
I20150416-16:27:15.261(-7)? FuFa6muAquumzfLMC
```

Any suggestions on what else I should log? Any idea what in `fast-render` could cause `waitOn` to be called many times?

**Comment by arunoda** [comment]
It should not.
May be try removing subs-manager use in the global route.

That may help.

**Comment by lorensr** [comment]
Commented out everything in the waitOn but the log, now the publish doesn't
run, but the waitOn still runs many times. Same behavior when user is
logged out. I guess okay to close, since I doubt I could produce a
reproduction outside my codebase.

**Comment by arunoda** [comment]
Okay. So, it's time to move to flow-router and think different on how to deal with subscriptions.
