### ISSUE TITLE
No data with flow-router without server side routes

### ISSUE THREAD

**Issue by wI2L** [meteorhacks/fast-render#107]
Hello @arunoda 

I am using flow-router in my app, and fast-render don't send data.
All my route are located under `lib/router/routes`, and i am not wrapping them with `Meteor.isClient`.

When i add server side routes for fast-render manually, it works.

Regarding this subscriptions, i have to say that it use `smart-publish` on the server and thoses publications use `this.userId`, but no arguments.
Could it be related ?

Regards,

William

**Comment by wI2L** [comment]
@arunoda 
I think this
> If you're doing some custom subscription handling, Fast Render won't be able to identify those subscriptions.

may be related to my issue.
Could you explain me what it means ?

**Comment by arunoda** [comment]
This means, if you are doing subscriptions outside FlowRouter's .subscriptions method, Fast Render can't identify subscriptions used in your app.

**Comment by wI2L** [comment]
Ok.
Still, i have some subscriptions made inside `FlowRouter.subscriptions` not catched by FastRender.

```
FlowRouter.route('/contacts', {

    name: 'contacts',
    subscriptions: function (params, queryParams) {
        this.register('contacts', Meteor.subscribe('contacts'));
    },
    action: function (params) {
        FlowLayout.render('appLayout', {
            main: 'contactsTemplate'
        });
    }
});
```
The publication is made with
```
Meteor.smartPublish("contacts", function () 
```

It doesn't work just like this. Tested with `FastRender.debugger.blockDDP()`

To make it work, i have to add on server
```
FastRender.route('/contacts', function (params) {
    this.subscribe('contacts');
});
```

**Comment by arunoda** [comment]
You need to put the router in a place it can be view in the server. Placing it on the lib folder is the ideal.

**Comment by wI2L** [comment]
All my routes are inside `lib/router/routes` ...then organized in a folder hierarchy.

**Comment by arunoda** [comment]
Then I think smartPublish is the issue. Fast Render can't identify data sent by it.

**Comment by wI2L** [comment]
Shouldn't it be the same problem with FastRender server side routes ?
```
FastRender.route('/contacts', function (params) {
    this.subscribe('contacts');
});
```
This is working very great, and my publication is untouched.

**Comment by arunoda** [comment]
Now I got it.
This is something with the latest version of Flow Router. Not something with fast-render.
Would you mind sending this to flow-router issue tracker.
I'll work on this.

**Comment by wI2L** [comment]
@arunoda Ok i'll do it.

**Comment by arunoda** [comment]
Let's close this.
