### ISSUE TITLE
Hard dependency on iron:router package name

### ISSUE THREAD

**Issue by joegoldbeck** [meteorhacks/fast-render#109]
I have a fork of iron:router with very little changed (a minor bug fix https://github.com/readFOLD/iron-router/commit/8570568c8f6c124e82325573fefe29e4e0a3c491 that hasn't yet made it into a release, and an updated "NO_ROUTES_TEMPLATE" fallback page https://github.com/readFOLD/iron-router/commit/5212a810b973c8afe76feaab4073094c43c63a60). However, fast-render won't recognize it, presumably due to the hard name dependency here https://github.com/meteorhacks/fast-render/blob/77dbf9c60d920626e494fdf29fa3e846bec93164/lib/server/iron_router_support.js .

Is there a way to make that dependency softer, or to pass in the package name as an option to fast-render? Happy to make a pull request for the latter (unless the package.js weak dependency breaks that approach), or the former (if you have an idea of where I'd start)

Thanks!

**Comment by zimme** [comment]
How about not changing the name of the package for your local copy, just add your version of `iron:router` to the packages folder in the project and have your version of `iron:router` be named `iron:router` and meteor will use the local version in the packages folder instead of the regular one.

**Comment by joegoldbeck** [comment]
Thanks for the suggestion! I suspect that would work, but wouldn't that mean I'd need to check my iron-router fork into my main project repo to have my project able to be checked out and straightforwardly deployed elsewhere? Seems odd from a version-control standpoint.

Do you know if there's a way to point to a git repo to add a package? That's how I'd solve this problem in plain Node.js.

**Comment by zimme** [comment]
Yeah, that's somethings that's lacking for the time being. Would be nice to add packages from git urls.

One thing you could do if you're using git is to add the package as a submodule in the packages folder, that way the package can have it's own version control and you'll be able to add it the same way to other projects too.

**Comment by joegoldbeck** [comment]
Cool. Thanks for letting me know! I wasn't sure if it was possible and I was just missing it. At the moment, I'm working off a forked fast-render to go with my forked iron-router. At the current level of complexity, that's probably less of a headache than submodules, but if I start using further packages with an iron-router dependency then submodules will probably be the way to go.

Now that I understand this a bit better, I think it's really more of a Meteor issue than a fast-render issue. Closing

**Comment by zimme** [comment]
No problem, Good luck in your endeavours. :+1:

**Comment by joegoldbeck** [comment]
Added a feature request on the Meteor trello on https://trello.com/c/mHK2dpr5
