### ISSUE TITLE
Processes null publications on every single request

### ISSUE THREAD

**Issue by dalgard** [meteorhacks/fast-render#113]
FastRender is processing null publications on every single request to the server, including simple resource requests such as image files etc.

Is this necessary?

It's not the best for performance; publish functions may not be entirely negligible.

**Comment by arunoda** [comment]
Did a fix for this.
Check the latest version. 
Also related to #111

**Comment by dalgard** [comment]
Awesome, thanks! And yes, exactly the same as #111.

**Comment by arunoda** [comment]
So, hope we can close this.
