### ISSUE TITLE
Fast Render + Template-level subscriptions

### ISSUE THREAD

**Issue by SachaG** [meteorhacks/fast-render#115]
What would be the best way to use Fast Render with template-level subscriptions?

Should I use `FastRender.route(callback)` to call Fast Render for every route where the template-level subscriptions are included? Or is there an easier way?

**Comment by arunoda** [comment]
That's the only way.
Since we can't render templates on the server, this is the only possible
way.

**Comment by SachaG** [comment]
Yeah that makes sense. Thanks :)
