### ISSUE TITLE
Uncaught TypeError: Cannot read property 'loginToken' of undefined 

### ISSUE THREAD

**Issue by udiedrichsen** [meteorhacks/fast-render#118]
Hi,

I am using the newest version of fast render and this message:
Uncaught TypeError: Cannot read property 'loginToken' of undefined meteorhacks_fast-render.js?834952f3d01a6c7bf69749f784905fbf54a4d81d:213
FastRender._securityCheck meteorhacks_fast-render.js?834952f3d01a6c7bf69749f784905fbf54a4d81d:213
FastRender.init meteorhacks_fast-render.js?834952f3d01a6c7bf69749f784905fbf54a4d81d:162
(anonymous function) meteorhacks_fast-render.js?834952f3d01a6c7bf69749f784905fbf54a4d81d:501
(anonymous function) meteorhacks_inject-data.js?4f682107cff01188a0cfe0f37cda14893b91575e:91
runStartupCallbacks meteor.js?4dc9757b244a30bdf37a732ac4db4026ce56fb6b:811
ready meteor.js?4dc9757b244a30bdf37a732ac4db4026ce56fb6b:813

I have NO accounts or a user in my app.
Maybe just a simple bug. Not every Meteor app has accounts :smile:

**Comment by rantav** [comment]
I see the same issue. Here's my stack trace: 

```
Uncaught TypeError: Cannot read property 'loginToken' of undefined
  FastRender._securityCheck @ fast_render.js:81
  FastRender.init @ fast_render.js:30
  (anonymous function) @ boot.js:2
  (anonymous function) @ client.js:9
  runStartupCallbacks @ startup_client.js:30
  ready @ startup_client.js:32
```

**Comment by rantav** [comment]
The problem seems to stem from InjectData. Not sure what's supposed to inject the data, but it isn't getting injected.
This returns an empty array: `$('script[type="text/inject-data"]', document.head)`


```
Meteor.startup(function() {
  var dom = $('script[type="text/inject-data"]', document.head); // dom is empty
  var injectedDataString = dom.text().trim();
  InjectData._data = InjectData._decode(injectedDataString) || {};
});

InjectData.getData = function(key, callback) {
  Meteor.startup(function() {
    callback(InjectData._data[key]); // hence we get here undefined
  });
};
```

**Comment by arunoda** [comment]
Here's the relative code and seems like I fixed it.
See: https://github.com/meteorhacks/fast-render/blob/79e9bab8a0d78a5dcf9f1e480ac3a11a5e688138/lib/client/fast_render.js#L83

May be you are running an older version?

**Comment by rantav** [comment]
@arunoda you are right. Although I updated fast-render before checking the bug, the update seemed to have  failed. 

So I removed and added again and now it's fixed. Thank you

**Comment by arunoda** [comment]
Hope we can fix this.
