### ISSUE TITLE
Crashes deploy to Modulus.io

### ISSUE THREAD

**Issue by flean** [meteorhacks/fast-render#119]
Once I removed fast-render I was able to deploy.

Servo is stuck in endless loop

```
/mnt/app/node_modules/fibers/future.js:278
						throw(ex);
						      ^
TypeError: Cannot read property 'master' of undefined
    at Object.Future.wait (/mnt/app/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at packages/accounts-base/accounts_common.js:141:1
    at /mnt/app/programs/server/packages/accounts-base.js:243:4
    at /mnt/app/programs/server/packages/accounts-base.js:1659:3
    at /mnt/app/programs/server/boot.js:222:10
    - - - - -
    at packages/mongo/mongo_driver.js:183:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

More logs: https://gist.github.com/arunoda/adde36ee2676a63ddde9
(edited by @arunoda)

**Comment by arunoda** [comment]
I'm quite not sure how fast-render relates this. It seems like something coming from the mongo package. We don't depend on that package as well.

Did you try to isolate this? I mean a minimal version I can try.

**Comment by flean** [comment]
Yes, I created a completely new app and just added fast render and it crashes modulus.io

**Comment by arunoda** [comment]
Okay. I'll check what's going on here.

**Comment by flean** [comment]
I use modulus deploy. Not sure if demeteorizer could be the culprit but wheb fast render is present it crashes.

**Comment by arunoda** [comment]
It should be demeteorizer issue. 
posting there would also is a good idea.
FR is a simple meteor package and it should work.

**Comment by flean** [comment]
I just tried everything again and it worked. I still have no clue what was going on, I didn't change anything just added fast-render back and tried on a modulus test server. It worked so I deployed to production and it also worked.
