### ISSUE TITLE
error on fast-rendering path: /comments?clientName=TestClient&clientId=y3wwYtCwCF4KGXKgQ&threadUrl=http:/localhost/&userEmail=&userAvatar= ; error: ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by alexreich** [meteorhacks/fast-render#121]
In the waitOn function in the route is the following line:

var clientOrigin = new URL(threadUrl).origin;

which generates this error:

error on fast-rendering path: /comments?clientName=TestClient&clientId=y3wwYtCwCF4KGXKgQ&threadUrl=http:/localhost/&userEmail=&userAvatar= ; error: ReferenceError: URL is not defined

URL is a Javascript function; is that not allowed?

Thanks!

**Comment by arunoda** [comment]
With FR, waitOn runs on both client and the server. That's the issue.
Check this: https://github.com/meteorhacks/fast-render#3-waiton-and-subscriptions-methods
