### ISSUE TITLE
TypeError: LocalCollection._idParse is not a function

### ISSUE THREAD

**Issue by darkship** [meteorhacks/fast-render#122]
Hi,
I'm  using Meteor Devel and due to some changes, fast-render seems not to be compatible with the next version (meteor/meteor@85ca501)

TypeError: LocalCollection._idParse is not a function meteorhacks_fast-render.js:347:133

**Comment by arunoda** [comment]
Yes it is. Since there is no release, I don't know how to do a release for a devel version.

**Comment by delgermurun** [comment]
Public 1.2 RC released.

**Comment by arunoda** [comment]
BTW: I already fixed this issue few days ago.
https://github.com/meteorhacks/fast-render/commit/f494a3c19bf7d17d1792c0c6342786220e40ae5b

**Comment by darkship** [comment]
thanks !
