### ISSUE TITLE
Exceptions in fast-render with meteor 1.1.0.3

### ISSUE THREAD

**Issue by Volodymyr-K** [meteorhacks/fast-render#129]
The fast-render doesn't seem to be working well with the latest version of meter v1.1.0.3
I see lots of these errors in the browser console:
```
Error: Exception in template helper:

> Before: 92246ms (diff: 92246ms)
    at usePostMessage (setimmediate.js:111)
    at setimmediate.js:140
    at meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:415
    at meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:1086
3reporters.js?1438765664819:67 Error: Exception in template helper:
```
I debugged these errors and they seem to be happening when the browser processes the ```<script type="text/inject-data">``` tag with the fast-render data.

Removing fast-render package or downgrading meteor makes the exceptions disappear.

**Comment by arunoda** [comment]
I tested with some apps and I couldn't replicate the issue.
Can you work on a sample repo.

**Comment by Volodymyr-K** [comment]
@arunoda Thanks for looking into this and sorry for having wasted your time. I did some more testing and the issue is not related to the new version of the meteor.

The problem is with the u2622:persistent-session package. Version 0.3.5 of that package works with fast-render, but when I update it to version 0.4.1 (the latest one today) I start getting these exceptions.

Do you know why fast-render is not compatible with u2622:persistent-session v0.4.1?

**Comment by arunoda** [comment]
Not sure. I never used that package.
