### ISSUE TITLE
Fast-render and publish composite

### ISSUE THREAD

**Issue by bitomule** [meteorhacks/fast-render#130]
Are those 2 packages compatible? I'm migrating to flow router and tried using fast-render too but I get errors caused publishComposite null returns. For example:

````
if(!this.userId){
return
}

It works well if I return a cursor instead of undefined or null. Is there a better way to work with this?

**Comment by arunoda** [comment]
What are the errors you are getting?

**Comment by bitomule** [comment]
I get 2 different errors as soon as I add fast-render package:

````
Publish handler for null sent no ready signal
````

and

````
RangeError: Maximum call stack size exceeded
````

**Comment by arunoda** [comment]
Is there any way you can isolate that code block and send it to me.

**Comment by bitomule** [comment]
I think I've found the issues:

- I'm using es6 for my model classes and I had some get variableName(). That's a really bad idea because cursors included that data in each document. So a get relatedData() using other cursors inside causes the stack error and multiple other issues I had.

- The other issue, the one that's still causing the "Publish handler for null sent no ready signal" is related to konecty:user-presence. I'm going to create an issue there too and reference this issue. Removing that package removes the error.

The only question left I have is: does that error cause any issues inside fast-render? Can I ignore it until is fixed on user-presence side or it could cause fast-render to crash.

Thanks @arunoda

**Comment by arunoda** [comment]
I really not sure without looking at a sample code.

**Comment by bitomule** [comment]
I've removed user-presence and added it again and now I don't see the error. Maybe an update fixed it. I don't think the issue is on fast render side. Thanks @arunoda

**Comment by arunoda** [comment]
Okay. Great.
