### ISSUE TITLE
FlowRouter and queryParams

### ISSUE THREAD

**Issue by Cerealkillerway** [meteorhacks/fast-render#131]
I use in my app flow-router 1.19.0 and fast-render 2.8.1;
I have a simple route that makes a subscription using "lang" queryParam to find data for the current language:

    PanelRoutes.route('/pages', {
        subscriptions: function(params, queryParams) {
            var options = {};
            options.fields = {
                _id: 1,
                code: 1
            };
            options.fields[queryParams.lang + '.title'] = 1;
            this.register("pagesList", subman.subscribe("findDocuments", 'Pages', {}, options));
        },
        action: function() {
            FlowLayout.render('panelLayout', {main: "pagesList"});
        } 
    });

and on next browser refresh I get this error in the console:

    error on fast-rendering path: /panel/pages?lang=en ; error: TypeError: Cannot read property 'lang' of undefined

Is it wrong/not possible to use queryParams with fast-render?

**Comment by arunoda** [comment]
This is an issue with FlowRouter and we've fixed in the latest version of FlowRouter. You need to use `kadira:flow-router` for this.
