### ISSUE TITLE
LocalCollection._idParse is not a function (METEOR@1.2-rc.4)

### ISSUE THREAD

**Issue by timbrandin** [meteorhacks/fast-render#132]
meteorhacks_fast-render.js:304 – Uncaught TypeError: LocalCollection._idParse is not a function

**Comment by arunoda** [comment]
Pushed a new version with a fix. Try installing the latest version. (`v2.9.0`)

**Comment by timbrandin** [comment]
Cool! :)

2015-08-23 19:55 GMT+02:00 Arunoda Susiripala <notifications@github.com>:

> Pushed a new version with a fix. Try installing the latest version. (
> v2.9.0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteorhacks/fast-render/issues/132#issuecomment-133883837>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by timbrandin** [comment]
LGTM :+1:

2015-08-23 19:56 GMT+02:00 Tim Brandin <tim.brandin@gmail.com>:

> Cool! :)
>
> 2015-08-23 19:55 GMT+02:00 Arunoda Susiripala <notifications@github.com>:
>
>> Pushed a new version with a fix. Try installing the latest version. (
>> v2.9.0)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/meteorhacks/fast-render/issues/132#issuecomment-133883837>
>> .
>>
>
>
>
> --
> Cheers,
> // Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
> http://timbrandin.com
> http://studiointeract.com
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by arunoda** [comment]
Closing this then :)
