### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'LocalCollection._idParse(msg.id)')

### ISSUE THREAD

**Issue by moooji** [meteorhacks/fast-render#134]
Fast-render (used by flow-router-ssr) does not seems to work anymore for me after upgrading to Meteor 1.2 RC7.

TypeError: undefined is not a function (evaluating 'LocalCollection._idParse(msg.id)')
_livedata_datameteorhacks_fast-render.js:304
onMessagelivedata_connection.js:252
(anonymous function)stream_client_sockjs.js:172
forEach
forEachunderscore.js:105
onmessagestream_client_sockjs.js:171
dispatchEventsockjs-0.3.4.js:87
_dispatchMessagesockjs-0.3.4.js:1072
_didMessagesockjs-0.3.4.js:1130
onmessagesockjs-0.3.4.js:1277
collection.js:164

**Comment by arunoda** [comment]
Do this add the updated fast-render to your app: `meteor add meteorhacks:fast-render`.
I'll do a release for SSR anyway now.

**Comment by moooji** [comment]
Wow, that was fast :) Yes, it works now again! Thx for all the great work with flow-router!

**Comment by arunoda** [comment]
Published updated SSR version to atmosphere as well.
