### ISSUE TITLE
Doesn't work with app-cache package

### ISSUE THREAD

**Issue by avalanche1** [meteorhacks/fast-render#136]
On first load data is injected just fine.
But on reload, when app.manifest is present in the browser's cache - fastRender is simply ignored by the browser and no html injection occurs.
Tested in Chrome 45 and Edge

**Comment by arunoda** [comment]
I think that what app-cache does. You need to avoid using app-cache.

**Comment by avalanche1** [comment]
And what about its benefits of caching js files? I want the best of both worlds!))

**Comment by arunoda** [comment]
I'm not an expert with appcache stuff. So, I'm not the best guy to answer this :)

May be if you find a way to use the appcache, only if your system goes offline.
But generally, you should not worry about appcache, unless you need to offline support.

**Comment by avalanche1** [comment]
I see. I'm not an expert either. But I'll amend the readme about this if you don't mind.

**Comment by arunoda** [comment]
Okay. Send me a PR.

**Comment by elie222** [comment]
Surely the advantage of appcache is faster page loads on subsequent visits? It's good for apps that don't need offline support too.
