### ISSUE TITLE
Some routes do not work via a "direct call" from the browser (using iron-router)

### ISSUE THREAD

**Issue by Strosch** [meteorhacks/fast-render#15]
Hi!

So I implemented fast-render into Questful but I am running into problems!
First I thought it is caused by the new version of iron-router but at least a part of it is definitely caused by fast-render!
Please see the whole description of the problem here: https://github.com/EventedMind/iron-router/issues/379

You can still find the version which is using fast-render and is experiencing these issues at http://questfultest.meteor.com/ .

Any ideas what could cause this?

Thanks! Cheers, P

**Comment by arunoda** [comment]
Hope this is no longer an issue.
