### ISSUE TITLE
Strange error server side

### ISSUE THREAD

**Issue by Lepozepo** [meteorhacks/fast-render#20]
Hi, I am running fast-render but I keep getting this error on random templates. What do you think it could be?

    error on fast-rendering path: /availability ; error: TypeError: Cannot read property 'collectionName' of undefined
    at packages/fast-render/lib/server/context.js:73
    at Array.forEach (native)
    at Context.subscribe (packages/fast-render/lib/server/context.js:71)
    at packages/fast-render/lib/server/iron_router_support.js:69
    at Array.forEach (native)
    at Context.onRoute (packages/fast-render/lib/server/iron_router_support.js:68)
    at packages/fast-render/lib/server/fast_render.js:43

**Comment by arunoda** [comment]
Hope we are good here.

**Comment by Lepozepo** [comment]
I believe so, I haven't had any issues anymore with this ^_^
