### ISSUE TITLE
Hack for Meteor.call/Meteor.apply?

### ISSUE THREAD

**Issue by wizonesolutions** [meteorhacks/fast-render#24]
So `accounts-password`, for example, will not fully render until it can do a password exchange with the server: https://github.com/meteor/meteor/blob/devel/packages/accounts-password/password_client.js#L27

Maybe this is the kind of thing that we don't want to render fast, but was interested in your thoughts.

![spendflow-5](https://f.cloud.github.com/assets/344116/2170084/2b53d1ce-9566-11e3-9e6d-462fd56948f6.png)

**Comment by arunoda** [comment]
Yes. That's based on Meteor's implementation.
