### ISSUE TITLE
FastRender.loggingIn()?

### ISSUE THREAD

**Issue by wizonesolutions** [meteorhacks/fast-render#25]
It seems using `Meteor.loggingIn()` to show the loading template until login is complete can cause an infinite loading screen with FastRender (because of how `accounts-password` manages `Meteor.loggingIn()`.

I wonder if there could be a workaround, or if there is some reactive way to easily check that FastRender has loaded a particular collection that I could use to get past that in cases where FastRender is active.

My loggingIn code in an Iron Router `before` hook:

````coffeescript
  if Meteor.loggingIn()
    console.log 'Logging in...'
    @render(@loadingTemplate)
    @stop()
````

**Comment by arunoda** [comment]
Hope we've worked on this and fixed the issue,
