### ISSUE TITLE
/robots.txt times out

### ISSUE THREAD

**Issue by Primigenus** [meteorhacks/fast-render#26]
http://q42.com/robots.txt broke when I deployed the site with fast-render enabled. It should return a 404 since the file does not exist. (I discovered the breakage because Google emailed me that robots.txt was returning an error)

The source code is available at http://github.com/q42/q42.nl.

When removing the fast-render package, /robots.txt works. With fast-render added, /robots.txt times out and doesn't return anything. It doesn't even hit a server-side route defined with iron-router that matches "*".

**Comment by arunoda** [comment]
Hope we are good here.
