### ISSUE TITLE
error on fast-rendering path: / : Cannot read property 'userId' of undefined

### ISSUE THREAD

**Issue by geekyme** [meteorhacks/fast-render#41]
Got this error immediately upon updating fast-render. 

<pre>
W20140416-21:01:37.593(8)? (STDERR) error on fast-rendering path: / ; error: TypeError: Cannot read property 'userId' of undefined
W20140416-21:01:37.595(8)? (STDERR)     at PublishContext.Meteor.methods.user-status-idle (packages/user-status/status.coffee:148:21)
W20140416-21:01:37.596(8)? (STDERR)     at Context.processPublication (packages/fast-render/lib/server/context.js:88)
W20140416-21:01:37.596(8)? (STDERR)     at packages/fast-render/lib/server/fast_render.js:64
W20140416-21:01:37.596(8)? (STDERR)     at Array.forEach (native)
W20140416-21:01:37.596(8)? (STDERR)     at Context.PublishContext.userId (packages/fast-render/lib/server/fast_render.js:61)
W20140416-21:01:37.596(8)? (STDERR)     at packages/fast-render/lib/server/fast_render.js:40
W20140416-21:01:37.596(8)? (STDERR)     at Array.forEach (native)
W20140416-21:01:37.596(8)? (STDERR)     at packages/fast-render/lib/server/fast_render.js:39
</pre>

**Comment by arunoda** [comment]
Hope we are good here.

**Comment by gcacars** [comment]
Now, for me shows "TypeError: Cannot read property 'subscriptions' of null"

Entire log:
W20150119-23:35:24.253(-2)? (STDERR) error on fast-rendering path: /produtos/categorias ; error: TypeError: Object function router(req, res, next) {                                                          // 13
W20150119-23:35:24.264(-2)? (STDERR)     //XXX this assumes no other routers on the parent stack which we should probably fix      // 14
W20150119-23:35:24.265(-2)? (STDERR)     router.dispatch(req.url, {                                                                // 15
W20150119-23:35:24.266(-2)? (STDERR)       request: req,                                                                           // 16
W20150119-23:35:24.267(-2)? (STDERR)       response: res                                                                           // 17
W20150119-23:35:24.269(-2)? (STDERR)     }, next);                                                                                 // 18
W20150119-23:35:24.269(-2)? (STDERR)   } has no method 'current'
W20150119-23:35:24.270(-2)? (STDERR)     at Object.route.waitOn (app/lib/routes.js:59:45)
W20150119-23:35:24.271(-2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/iron_router_support.js:83:1
W20150119-23:35:24.272(-2)? (STDERR)     at Array.forEach (native)
W20150119-23:35:24.274(-2)? (STDERR)     at Context.onRoute (packages/meteorhacks:fast-render/lib/server/iron_router_support.js:82:1)
W20150119-23:35:24.275(-2)? (STDERR)     at Object._processRoutes (packages/meteorhacks:fast-render/lib/server/routes.js:60:1)
W20150119-23:35:24.278(-2)? (STDERR)     at onRoute (packages/meteorhacks:fast-render/lib/server/routes.js:20:1)
W20150119-23:35:24.279(-2)? (STDERR)     at doCall (packages/meteorhacks:picker/lib/implementation.js:98:1)
W20150119-23:35:24.280(-2)? (STDERR)     at [object Object].PickerImp._processRoute (packages/meteorhacks:picker/lib/implementation.js:92:1)
W20150119-23:35:24.282(-2)? (STDERR)     at processNextRoute (packages/meteorhacks:picker/lib/implementation.js:60:1)
W20150119-23:35:24.288(-2)? (STDERR)     at processNextMiddleware (packages/meteorhacks:picker/lib/implementation.js:48:1)
W20150119-23:35:24.293(-2)? (STDERR) error on fast-rendering path: /produtos/categorias ; error: TypeError: Cannot read property 'subscriptions' of null
W20150119-23:35:24.294(-2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:31:1
W20150119-23:35:24.295(-2)? (STDERR)     at handleError (packages/meteorhacks:fast-render/lib/server/routes.js:96:1)
W20150119-23:35:24.296(-2)? (STDERR)     at Object._processRoutes (packages/meteorhacks:fast-render/lib/server/routes.js:63:1)
W20150119-23:35:24.297(-2)? (STDERR)     at onRoute (packages/meteorhacks:fast-render/lib/server/routes.js:20:1)
W20150119-23:35:24.298(-2)? (STDERR)     at doCall (packages/meteorhacks:picker/lib/implementation.js:98:1)
W20150119-23:35:24.298(-2)? (STDERR)     at [object Object].PickerImp._processRoute (packages/meteorhacks:picker/lib/implementation.js:92:1)
W20150119-23:35:24.299(-2)? (STDERR)     at processNextRoute (packages/meteorhacks:picker/lib/implementation.js:60:1)
W20150119-23:35:24.300(-2)? (STDERR)     at processNextMiddleware (packages/meteorhacks:picker/lib/implementation.js:48:1)
W20150119-23:35:24.301(-2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:41:1
W20150119-23:35:24.303(-2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:83:1
W20150119-23:35:24.304(-2)? (STDERR) 
W20150119-23:35:24.304(-2)? (STDERR) /home/gcacars/.meteor/packages/meteor-tool/.1.0.38.1ipopqt++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150119-23:35:24.306(-2)? (STDERR) 						throw(ex);
W20150119-23:35:24.307(-2)? (STDERR) 						      ^
W20150119-23:35:24.307(-2)? (STDERR) TypeError: Cannot read property 'subscriptions' of null
W20150119-23:35:24.308(-2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:31:1
W20150119-23:35:24.309(-2)? (STDERR)     at handleError (packages/meteorhacks:fast-render/lib/server/routes.js:96:1)
W20150119-23:35:24.310(-2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:85:1

**Comment by arunoda** [comment]
Can we have a sample code for this issue. Better if it's a repo. And create another issue.
