### ISSUE TITLE
Expected not to find a document already present for an add

### ISSUE THREAD

**Issue by DenisGorbachev** [meteorhacks/fast-render#49]
Hi Arunoda,

![image](https://cloud.githubusercontent.com/assets/829578/3141032/9ee1084e-e95f-11e3-9256-4c1b16be644b.png)

When server sends an object that is already present on client via fast-render, the client throws this error. The issue doesn't manifest on localhost, only on production servers (both Modulus and Galaxy). You can see it in https://pintask.me/: just log in and reload the page.

Also, it's evident that the number of errors (236 on screenshot) is correlated to number of fastrendered objects. Here's a simple test:

* Open one board in Pintask
* Reload the page.
* Note the number of errors
* Execute `Cards.find({boardId: Router.current().params.boardId, isArchived: false}).count() + Lists.find({boardId: Router.current().params.boardId}).count()`
* Open another board
* /* Do the same */

It's clear that difference between error counts is equal to difference between fastrendered cards+lists sums.

This error is present on both projects I'm involved in, and both projects use latest Meteor 0.8.1.3 + latest fast-render 0.2.5

**Comment by arunoda** [comment]
Hope we are good here.
