### ISSUE TITLE
Compatibility with Tinytest

### ISSUE THREAD

**Issue by DominikGuzei** [meteorhacks/fast-render#51]
Hey there!

I tried to test a standalone package that requires fast-render using Tinytest and it fails to run the `mrt test-packages` command because of the `isIronRouterExists()` function within `package.js`.

My package is not contained within a meteor application and I don't think it should be a requirement to test it ;-)

I could resolve the issue by adding `.meteor/packages` and putting `iron-router` into it. But then there is another error when starting the tests:

`ReferenceError: Router is not defined
W20140610-17:59:05.670(2)? (STDERR)     at waitOnFunction (packages/fast-render/lib/server/iron_router_support.js:13)`

What should I do?

**Comment by arunoda** [comment]
Hope we are good here.
