### ISSUE TITLE
Populate collection earlier

### ISSUE THREAD

**Issue by scaljeri** [meteorhacks/fast-render#57]
I need collection data to be available for the routes setup as I've asked [here](http://stackoverflow.com/questions/25422567/meteor-iron-router-how-to-define-routes-using-data-from-settings-json/25423955#25423955). The problem is that in order to do something like this:

    path: Settings.findOne().basePath + '/....'

the collections need to be initialized before the routes. I noticed that it is the other way around because the fast-render code is added at the end of the head section. Is there anyway this can be fixed ?

**Comment by arunoda** [comment]
These are the only features we've. 
See docs: https://github.com/meteorhacks/fast-render#using-fast-render-with-iron-router
