### ISSUE TITLE
[Question] FastRender in Iron Router's onBeforeAction?

### ISSUE THREAD

**Issue by tixpaul** [meteorhacks/fast-render#60]
Hi

I've been playing around with FastRender today, and all of my subscriptions are in the ```onBeforeAction``` function. I ended up doing away with ```waitOn``` entirely because I can do things like:

``` javascript
var topicMap = this.data().articles.map(function(p){ return p.topic });
this.subscribe("TopicsById", topicIds);
 ```
And then send the specific id's to my publish function so that I'm not publishing anything that's not required.

However because I'm not using ```waitOn```, I started using the method in option 3 at: https://meteorhacks.com/fast-render/iron-router-support/. This had me writing a whole bunch of:
``` javascript
FastRender.route('/', function(params){
  this.find('articles', {}, {limit: 20, sort: {receivedAt: -1}});
  this.completeSubscriptions(['ArticleList']);
});
``` 
functions which felt like I was repeating myself in areas I'd abstracted by sharing a controller across several routes.

Is there any way to utilize fast render in my ```onBeforeAction``` functions? eg/ I can call ```FastRender.completeSubscriptions``` from there. Is there a way to use the ```this.find``` that I'm using in ```FastRender.route(...)``` there as well? Or is there just something about iron-router and fast-render that I'm not understanding?

Thanks

**Comment by arunoda** [comment]
Please check docs: https://github.com/meteorhacks/fast-render#using-fast-render-with-iron-router
