### ISSUE TITLE
Sending Session data?

### ISSUE THREAD

**Issue by marpett** [meteorhacks/fast-render#73]
I'm sending some data to the client via Meteor.call's (static data that doesn't have to be reactive), and store them in Session on the client. That way I get UI reactivity after I store the data in Session, since Meteor.call is asynchronous, this is the only way I figured how to make this work.
My question is, fast-render doesn't send the Session data with the initial page load it seems. Is there a reason for that? Something that could be added?

**Comment by arunoda** [comment]
Fast Render can't handle session data since this happens when processing page in the server.
Anyway, you should not use session inside waitOn.
