### ISSUE TITLE
Angular behavior

### ISSUE THREAD

**Issue by ArthurianX** [meteorhacks/fast-render#76]
This is not a bug, the issue is that I am beginning with meteor and this module sounds really great.

The issue is that I don't grasp yet the full picture of Meteor and this module.

Now, my question is how will it fast-render content from the server in a angular application (urigo:angular) ?
Of the top of my head I know that we still have to wait for the angular app to bootstrap itself before showing content, so even if the content arrives quicker we still have the bootstrap and content processing time, right?

**Comment by arunoda** [comment]
I hope now this works well with angular. You can use our route APIs for that: https://github.com/meteorhacks/fast-render#using-fast-renders-route-apis

I'm closing this issue since, we don't specifically add angular related features into FR.
