### ISSUE TITLE
processRoutes() in lib/server/iron_router_support.js is not looking up the route controller correctly

### ISSUE THREAD

**Issue by jfly** [meteorhacks/fast-render#84]
I'm referring to the following code:

```javascript
function processRoutes() {
  Router.routes.forEach(function(route) {
    route.options = route.options || {};
    if(route.options.fastRender) {
      handleRoute(route);
    } else if(
        route.options.controller && 
        route.options.controller.prototype &&
        route.options.controller.prototype.fastRender
    ) {
      handleRoute(route);
    }
  });
```

In my debugging, I found that `route.options.controller` is just a string. In https://github.com/EventedMind/iron-router/commit/6866776e450a4a5b50191956ca09d072b583b2f0#diff-f34e409694d3ba334dabbea190f64c1dR80 there's a `findControllerConstructor()` method on routes that does what we want. Would you like me to submit a pull request with this change?

**Comment by arunoda** [comment]
We've fixed this.
