### ISSUE TITLE
bug with Meteor.logoutOtherClients()

### ISSUE THREAD

**Issue by Goluis** [meteorhacks/fast-render#86]
while programming quietly in my application I met a very strange bug that I had no idea where it came from
```javascript
Uncaught Error: seems like cookie tossing is happening. visit here: http://git.io/q4IRHQ 
```
after reading recommendations on fast-render about cookie tosting I not found the solution so I started to read my code thinking it was my mistake until I found the error
```javascript
Tracker.autorun(function () {
  if(Meteor.loggingIn()) {
    Meteor.logoutOtherClients();
  }
});
```
the above code works pretty well but when **Meteor.logoutOtherClients();** is executed and the page is reloaded the error start and fast-render stop

i think that is caused because **Meteor.logoutOtherClients()** change the Meteor.loginToken and **FastRender._securityCheck** fails

**Comment by arunoda** [comment]
Hope this is fixed. Let me know, if it's not.

**Comment by kidchenko** [comment]
@arunoda I'm the same problem.

**Comment by adamthewan** [comment]
Same here for me, cookie tossing happens sometimes during logout. Infrequent but reproducible error.
