### ISSUE TITLE
Refresh rate jumps to 10 seconds.

### ISSUE THREAD

**Issue by Lenin7** [meteorhacks/fast-render#93]
Refresh rate jumps to 10 seconds after adding fast-render. Is there any way to lower the refresh rate?
My current refresh rate without fast-render is 3 seconds.

Thanks!

**Comment by arunoda** [comment]
What do you mean by refresh rate?

**Comment by Lenin7** [comment]
Sorry, I meant the refresh rate at which the mongo driver polls for changes in Mongo.
Thanks

**Comment by arunoda** [comment]
Sorry. I've no idea about this.
But you should use oplog.
