### ISSUE TITLE
[Cordova] Update from 2.1.6 to 2.3.0 gets app stuck on splash screen

### ISSUE THREAD

**Issue by fungilation** [meteorhacks/fast-render#94]
After meteor update on a bunch of packages, my cordova app got stuck on splash screen. Isolated packages responsible to Fast render:

```
meteorhacks:fast-render  upgraded from 2.1.6 to 2.3.0
meteorhacks:inject-data  added, version 1.2.1
meteorhacks:picker       added, version 1.0.1
```

After reversing the above in .meteor/versions, cordova app loads correctly again.

**Comment by arunoda** [comment]
That means, newest fast render cause the issue?
Can you see any kind of client errors? Does this happen on locally too?

Any help to reproduce this locally?

**Comment by fungilation** [comment]
Yes, as I isolated upgrading all other packages except the above 3 does not cause the app to hang on splash screen. On browser, this isn't an issue, with or without the latest fast-render. Only fails In cordova on iOS. The last line in xcode console when app is stuck on splash screen:

```
2015-01-27 16:41:31.859 ClubChat[67287:853544] METEOR CORDOVA DEBUG loading filepath: /Data/garyfung/Library/Developer/CoreSimulator/Devices/FDDD1AC3-98B3-48B6-B331-A5E07663087B/data/Containers/Bundle/Application/D8F9BFEE-59F8-42F7-9C9D-F05B969FE294/ClubChat.app/www/application/fonts/fontawesome-webfont.woff for path: %2Ffonts%2Ffontawesome-webfont.woff
```

Sorry for not having an exact test case. There's no client errors other than app being stuck in cordova splash screen, before Meteor.startup gets run (I tried a console.log there). So I gather it has to be something to do with load order of cordova / iOS native plugins being interfered with with the new fast-render and related packages.

**Comment by arunoda** [comment]
Okay. I'll try to do it with a cordova app my own. Let's see.

**Comment by pmwisdom** [comment]
Same thing happened to me using iOS. And after I updated very recently an error along the lines of "Unexpected Syntax Error" started appearing right before startup, causing strange issues until I removed fast-render. After I took it out, iOS started also working.

**Comment by arunoda** [comment]
If then, try to use the older version for now.
It will do a test and fix this.

**Comment by arunoda** [comment]
I made a fix and released a new version.
Hope it should fix this issue.

**Comment by fungilation** [comment]
Nice! it works on 2.3.1. Thanks

**Comment by arunoda** [comment]
Great.
